### PR TITLE
ENH PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by emteknetnz**
Issue https://github.com/silverstripe/silverstripe-framework/issues/10250

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Builds are failing - can you please take a look?

**Comment by emteknetnz** [comment]
`.travis.yml` required a ^4 of webauthn, which is currently not php 8.1 compatible.  I've changed to 4.x-dev, it'll still fail until https://github.com/silverstripe/silverstripe-webauthn-authenticator/pulls is merged

**Review by GuySartorelli — APPROVED** [review]
For posterity: See discussion in silverstripe/silverstripe-admin#1294 about the general approach. tl;dr:
> the purposes of this PR is to avoid passing null (specifically null) from built-in functions that as of php 8.1 will throw deprecation warnings if null is passed in. The approach is necessarily heavy-handed, and while there are many situations where it isn't needed, it would be prohibitively laborious to find all of those situations by hand.

Looks good to me - but @emteknetnz can you please validate that the travis build not failing is okay? Based on your previous comment it sounds like it was expected to fail?

**Comment by emteknetnz** [comment]
Ah, might have been this older commit that was required - https://github.com/silverstripe/silverstripe-webauthn-authenticator/commit/371c5bbb08dc793ff46f053e5bf09a5d76ecbf10

**Comment by GuySartorelli** [comment]
Sweet. I'll add this to my merge list for this afternoon.

**Pull request merged**
